apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
  labels:
    name: prometheus

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: carol
  namespace: prometheus

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-cluster-role
rules:
  - apiGroups: [""] # "" означает apiGroup под именем core или legacy
    resources: ["pods"]
    verbs: ["get", "watch", "list"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-bind
  namespace: prometheus
subjects:
  - kind: Group
    name: system:serviceaccounts:prometheus
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: clusterrole-prometheus
  apiGroup: rbac.authorization.k8s.io
