backend:
  type: es
  es:
    host: elasticsearch-master

filter:
  mergeJSONLog: true
  mergeLogKey: "app"

tolerations:
  - key: node-role
    operator: Equal
    value: infra
    effect: NoSchedule
    
rawConfig: |
  @INCLUDE fluent-bit-service.conf
  @INCLUDE fluent-bit-input.conf
  @INCLUDE fluent-bit-filter.conf
  @INCLUDE fluent-bit-output.conf
