apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
 name: web
 labels: # Метки в формате key: value
  app: web
spec: # Описание Pod
 containers: # Описание контейнеров внутри Pod
 - name: web
   image: mechanik88/web:v1